<template>
  <div>
    <ENavTitlebar />
    <ENavBar>
      <ENavBtn
        icon="devices"
        label="sidebar"
        to="/sidebar"
      /><ENavBtn
        icon="devices"
        label="navbar"
        to="/navbar"
      /><ENavBtn
        icon="palette"
        label="colors"
        to="colors"
      />
    </ENavBar>
  </div>
</template>
